### ISSUE TITLE
Ask for papers

### ISSUE THREAD

**Issue by Federico2014** [kehm/ehrblockchain#1]
Hi, kehm, I am interested in you projects and want to learn from your research, but I can't be able to download your  two papers, Can you send them to my email: zhenping1989@126.com , Thank you very much.

**Comment by kehm** [comment]
Hi there,
The papers can be downloaded from https://onlinelibrary.wiley.com/doi/10.1002/cpe.5479 and http://bora.uib.no/handle/1956/20519
