### ISSUE TITLE
ask for the full list of code

### ISSUE THREAD

**Issue by Federico2014** [kehm/ehrblockchain#2]
Hi, kehm, can you provide a complete source code, otherwise it can't run. Thank you 

zp@zp-Lenovo-CHAO5000:~/projects/ehrblockchain$ ./generate.sh 
Running Cryptogen:Start
./generate.sh: line 9: ../bin/cryptogen: No such file or directory

**Comment by kehm** [comment]
Hi Federico and thanks for your interest,
Cryptogen is part of the Fabric binaries https://github.com/hyperledger/fabric-samples

You can read more about Cryptogen here https://hyperledger-fabric.readthedocs.io/en/release-1.4/commands/cryptogen.html
