### ISSUE TITLE
When I run "./start.sh [seconds]" to start docker containers, I come up with the problem

### ISSUE THREAD

**Issue by VolcanoWCAN** [kehm/ehrblockchain#3]
Hi, 
    I'm very interested in your work named ehrblockchain. When I run the program, an error is reported. And I search about the question on the Internet, but it doesn't work.
    I run "./start.sh [seconds]" to start docker containers, the logs output as follows：

ERROR: for peer0.practitioner1.example.com  Cannot start service peer0.practitioner1.example.com: Invalid address 172.18.0.80: It does not belong to any of this network's subnets
Creating peer0.pharmacy1.example.com        ... error

ERROR: for peer0.pharmacy1.example.com  Cannot start service peer0.pharmacy1.example.com: Invalid address 172.18.0.60: It does not belong to any of this network's subnets
Creating peer1.practitioner1.example.com    ... error

ERROR: for peer1.practitioner1.example.com  Cannot start service peer1.practitioner1.example.com: Invalid address 172.18.0.90: It does not belong to any of this network's subnets

ERROR: for peer0.pharmacy1.example.com  Cannot start service peer0.pharmacy1.example.com: Invalid address 172.18.0.60: It does not belong to any of this network's subnets

ERROR: for orderer0.pharmacy1.example.com  Cannot start service orderer0.pharmacy1.example.com: Invalid address 172.18.0.110: It does not belong to any of this network's subnets

ERROR: for orderer0.practitioner1.example.com  Cannot start service orderer0.practitioner1.example.com: Invalid address 172.18.0.120: It does not belong to any of this network's subnets

ERROR: for peer1.hospital1.example.com  Cannot start service peer1.hospital1.example.com: Invalid address 172.18.0.50: It does not belong to any of this network's subnets

ERROR: for peer1.practitioner1.example.com  Cannot start service peer1.practitioner1.example.com: Invalid address 172.18.0.90: It does not belong to any of this network's subnets

ERROR: for peer1.pharmacy1.example.com  Cannot start service peer1.pharmacy1.example.com: Invalid address 172.18.0.70: It does not belong to any of this network's subnets

ERROR: for couchdb0  Cannot start service couchdb0: ttrpc: closed: unknown

ERROR: for orderer0.hospital1.example.com  Cannot start service orderer0.hospital1.example.com: Invalid address 172.18.0.100: It does not belong to any of this network's subnets

ERROR: for peer0.practitioner1.example.com  Cannot start service peer0.practitioner1.example.com: Invalid address 172.18.0.80: It does not belong to any of this network's subnets
ERROR: Encountered errors while bringing up the project.

**Comment by VolcanoWCAN** [comment]
I opened compose-with-raft.yaml and modified the information such as: 
ehrnetwork: ipv4_address: 172.21.0.90. --->   my docker ipv4 ip
The program continue to run, and the log shows as follows.
I want to know if I've run it successfully.

logs:
Creating docker containers:Start
couchdb0 is up-to-date    
couchdb2 is up-to-date   
couchdb4 is up-to-date     
Starting orderer0.pharmacy1.example.com ...    
Starting orderer0.hospital1.example.com ...      
ca.hospital1.example.com is up-to-date       
Starting orderer0.practitioner1.example.com ...   
couchdb1 is up-to-date
ca.pharmacy1.example.com is up-to-date
Starting orderer0.pharmacy1.example.com ... done
Starting orderer0.hospital1.example.com ... done
Starting orderer0.practitioner1.example.com ... done
Starting peer0.hospital1.example.com ... done
Starting peer0.pharmacy1.example.com ... done
Starting peer0.practitioner1.example.com ... done
Starting peer1.hospital1.example.com ... done
Starting peer1.pharmacy1.example.com ... done
Starting peer1.practitioner1.example.com ... done
cli0 is up-to-date
Creating docker containers:Done
Waiting s for orderers to get ready
Sleep: invalid time interval 's'
Try 'sleep --help' for more information.

**Comment by kehm** [comment]
Hi,
start.sh takes an amount of seconds (in the form of a number) as an argument to the sleep function.
Try running "./start.sh 20" where the number 20 represents "20 seconds".
