### ISSUE TITLE
some questions about starting the project

### ISSUE THREAD

**Issue by VolcanoWCAN** [kehm/ehrblockchain#4]
Hi，

I'd like to talk about the problems when I run the project： 
First，start the fabric network.  When I run. / generate.sh,  it runs successfully.
Then I run. / start.sh, and I got an error. 
The logs are as follows:

Creating docker containers:Start
Creating volume "ehrnetwork_peer0.pharmacy1.example.com" with default driver
Creating volume "ehrnetwork_peer0.practitioner1.example.com" with default driver
Creating volume "ehrnetwork_ca.pharmacy1.example.com" with default driver
Creating volume "ehrnetwork_ca.hospital1.example.com" with default driver
Creating volume "ehrnetwork_ca.practitioner1.example.com" with default driver
Creating volume "ehrnetwork_orderer0.practitioner1.example.com" with default driver
Creating volume "ehrnetwork_peer1.hospital1.example.com" with default driver
Creating volume "ehrnetwork_orderer0.pharmacy1.example.com" with default driver
Creating volume "ehrnetwork_peer1.practitioner1.example.com" with default driver
Creating volume "ehrnetwork_peer1.pharmacy1.example.com" with default driver
Creating volume "ehrnetwork_orderer0.hospital1.example.com" with default driver
Creating volume "ehrnetwork_peer0.hospital1.example.com" with default driver
Creating couchdb5 ... 
Creating couchdb2 ... 
Creating orderer0.hospital1.example.com     ... error
Creating ca.pharmacy1.example.com       ... 
Creating ca.hospital1.example.com       ... 
Creating ca.practitioner1.example.com   ... 
Creating orderer0.pharmacy1.example.com ... 
Creating orderer0.practitioner1.example.com ... 
Creating couchdb1                           ... 
Creating couchdb3                           ... 
Creating couchdb2                           ... done
Creating couchdb0                           ... 
Creating couchdb5                           ... done
Creating ca.hospital1.example.com           ... done
d only when connecting to networks with user configured subnets

ERROR: for orderer0.practitioner1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets

ERROR: for orderer0.pharmacy1.example.com  user specified IP address is supporteCreating ca.practitioner1.example.com       ... done
Creating peer0.pharmacy1.example.com        ... error

ERROR: for peer0.pharmacy1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
Creating peer1.practitioner1.example.com    ... error
Creating couchdb0                           ... done
ERROR: for peer1.practitioner1.example.com  user specified IP address is supportCreating couchdb4                           ... done
Creating couchdb1                           ... done
Creating couchdb3                           ... done
ERROR: for peer0.hospital1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
Creating peer0.practitioner1.example.com    ... error
ERROR: for peer0.practitioner1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
Creating peer1.hospital1.example.com        ... error
ERROR: for peer1.hospital1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
Creating peer1.pharmacy1.example.com        ... error
ERROR: for peer1.pharmacy1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for peer0.pharmacy1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for peer0.practitioner1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for orderer0.practitioner1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for peer1.hospital1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for orderer0.pharmacy1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for peer1.practitioner1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for peer1.pharmacy1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for orderer0.hospital1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: for peer0.hospital1.example.com  user specified IP address is supported only when connecting to networks with user configured subnets
ERROR: Encountered errors while bringing up the project.

I find that in crypto-config.yaml,   the SANS is:
          - "localhost"
          - "172.18.0.70"
So I should do somthing with the subnet. However, I don't know how to do.
**Could you please give me some instructions about this error？**

Then I run the client side.
First, put certs.jks in the / SRC / main / resources directory.
Then, edit attachments.txt. But I have a problem here. ——Finally, add IP address - hostname mappings to the system hosts file.

**what should I do ？It says add hostname address mappings in the system hosts file (located at /etc/hosts in Linux). But I don‘t know how to do with it.
Could you please give me an example？**

**Should I install postgresql before I run java application？**

**Comment by VolcanoWCAN** [comment]
I had solved all the problems about the setup of the project.
Thank you very much!
Excellent project!

**Comment by dkxiaohei** [comment]
> Hi，
> 
> I'd like to talk about the problems when I run the project：
> First，start the fabric network. When I run. / generate.sh, it runs successfully.
> Then I run. / start.sh, and I got an error.
> The logs are as follows:
> 
> Creating docker containers:Start
> Creating volume "ehrnetwork_peer0.pharmacy1.example.com" with default driver
> Creating volume "ehrnetwork_peer0.practitioner1.example.com" with default driver
> Creating volume "ehrnetwork_ca.pharmacy1.example.com" with default driver
> Creating volume "ehrnetwork_ca.hospital1.example.com" with default driver
> Creating volume "ehrnetwork_ca.practitioner1.example.com" with default driver
> Creating volume "ehrnetwork_orderer0.practitioner1.example.com" with default driver
> Creating volume "ehrnetwork_peer1.hospital1.example.com" with default driver
> Creating volume "ehrnetwork_orderer0.pharmacy1.example.com" with default driver
> Creating volume "ehrnetwork_peer1.practitioner1.example.com" with default driver
> Creating volume "ehrnetwork_peer1.pharmacy1.example.com" with default driver
> Creating volume "ehrnetwork_orderer0.hospital1.example.com" with default driver
> Creating volume "ehrnetwork_peer0.hospital1.example.com" with default driver
> Creating couchdb5 ...
> Creating couchdb2 ...
> Creating orderer0.hospital1.example.com ... error
> Creating ca.pharmacy1.example.com ...
> Creating ca.hospital1.example.com ...
> Creating ca.practitioner1.example.com ...
> Creating orderer0.pharmacy1.example.com ...
> Creating orderer0.practitioner1.example.com ...
> Creating couchdb1 ...
> Creating couchdb3 ...
> Creating couchdb2 ... done
> Creating couchdb0 ...
> Creating couchdb5 ... done
> Creating ca.hospital1.example.com ... done
> d only when connecting to networks with user configured subnets
> 
> ERROR: for orderer0.practitioner1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> 
> ERROR: for orderer0.pharmacy1.example.com user specified IP address is supporteCreating ca.practitioner1.example.com ... done
> Creating peer0.pharmacy1.example.com ... error
> 
> ERROR: for peer0.pharmacy1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> Creating peer1.practitioner1.example.com ... error
> Creating couchdb0 ... done
> ERROR: for peer1.practitioner1.example.com user specified IP address is supportCreating couchdb4 ... done
> Creating couchdb1 ... done
> Creating couchdb3 ... done
> ERROR: for peer0.hospital1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> Creating peer0.practitioner1.example.com ... error
> ERROR: for peer0.practitioner1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> Creating peer1.hospital1.example.com ... error
> ERROR: for peer1.hospital1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> Creating peer1.pharmacy1.example.com ... error
> ERROR: for peer1.pharmacy1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for peer0.pharmacy1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for peer0.practitioner1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for orderer0.practitioner1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for peer1.hospital1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for orderer0.pharmacy1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for peer1.practitioner1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for peer1.pharmacy1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for orderer0.hospital1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: for peer0.hospital1.example.com user specified IP address is supported only when connecting to networks with user configured subnets
> ERROR: Encountered errors while bringing up the project.
> 
> I find that in crypto-config.yaml, the SANS is:
> - "localhost"
> - "172.18.0.70"
> So I should do somthing with the subnet. However, I don't know how to do.
> **Could you please give me some instructions about this error？**
> 
> Then I run the client side.
> First, put certs.jks in the / SRC / main / resources directory.
> Then, edit attachments.txt. But I have a problem here. ——Finally, add IP address - hostname mappings to the system hosts file.
> 
> **what should I do ？It says add hostname address mappings in the system hosts file (located at /etc/hosts in Linux). But I don‘t know how to do with it. Could you please give me an example？**
> 
> **Should I install postgresql before I run java application？**

how did you solve it ? Thanks you~
