### ISSUE TITLE
peer0.hospital1.example.com有报错，其他的peer没有问题~

### ISSUE THREAD

**Issue by dkxiaohei** [kehm/ehrblockchain#7]
ERROR Channel - 
Channel Channel{id: 1, name: providerschannel} 
Sending proposal with transaction: 4dd38f18bef2a2c1b9a0cde059cfdfd0db04009ada878c9d1cb01be627acc0da to 
Peer{ id: 2, name: peer0.hospital1.example.com, channelName: providerschannel, url: grpcs://172.18.0.40:7051} 
failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [providerschannel] creator org [Hospital1MSP], cause=null}
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [providerschannel] creator org [Hospital1MSP]

**Comment by kehm** [comment]
I suppose that this is related to some certificate, IP or msp configuration mismatch
