### ISSUE TITLE
./start.sh has error

### ISSUE THREAD

**Issue by smartking260** [kehm/ehrblockchain#8]
Hi,
I run "./start.sh " to start docker containers, the logs output as follows：
root@ghasem-p:~/fabric-samples/ehrblockchain-master# ./start.sh 20
Creating docker containers:Start
Removing orderer0.practitioner1.example.com
Removing orderer0.pharmacy1.example.com
Removing orderer0.hospital1.example.com
Removing peer1.hospital1.example.com
Removing peer0.practitioner1.example.com
Removing peer1.pharmacy1.example.com
Removing peer0.pharmacy1.example.com
Removing peer0.hospital1.example.com
couchdb1 is up-to-date
couchdb2 is up-to-date
Recreating 6ebadec4cd8b_orderer0.practitioner1.example.com ... 
ca.hospital1.example.com is up-to-date
Recreating 03211a7c7dd0_orderer0.hospital1.example.com     ... 
couchdb4 is up-to-date
couchdb5 is up-to-date
ca.pharmacy1.example.com is up-to-date
Recreating 26c8db6a9db4_orderer0.pharmacy1.example.com     ... 
couchdb0 is up-to-date
ca.practitioner1.example.com is up-to-date
Recreating 5478716873b6_peer1.hospital1.example.com        ... 
couchdb3 is up-to-date
Recreating cfda099fdde0_peer0.pharmacy1.example.com        ... 
Recreating 642f70c49dd4_peer0.practitioner1.example.com    ... 
Recreating 26c8db6a9db4_orderer0.pharmacy1.example.com     ... error
Recreating b1822f40f44e_peer0.hospital1.example.com        ... 
Recreating c3c15520eb6d_peer1.pharmacy1.example.com        ... 

ERROR: for peer1.practitioner1.example.com  Cannot start service peer1.practitioner1.example.com: Invalid address 172.21.0.90: It does not belong to any of thisRecreating 6ebadec4cd8b_orderer0.practitioner1.example.com ... error

ERROR: for 26c8db6a9db4_orderer0.pharmacy1.example.com  Cannot start service ordRecreating b1822f40f44e_peer0.hospital1.example.com        ... error
 any of this network's subnets

ERROR: for b1822f40f44e_peer0.hospital1.example.com  Cannot start service peer0.Recreating 5478716873b6_peer1.hospital1.example.com        ... error
 this network's subnets

ERROR: for 6ebadec4cd8b_orderer0.practitioner1.example.com  Cannot start service orderer0.practitioner1.example.com: Invalid address 172.18.0.120: It does not bRecreating cfda099fdde0_peer0.pharmacy1.example.com        ... error

ERROR: for 5478716873b6_peer1.hospital1.example.com  Cannot start service peer1.hospital1.example.com: Invalid address 172.18.0.50: It does not belong to any of this network's subnets
Recreating 03211a7c7dd0_orderer0.hospital1.example.com     ... error
ERROR: for cfda099fdde0_peer0.pharmacy1.example.com  Cannot start service peer0.pharmacy1.example.com: Invalid address 172.18.0.60: It does not belong to any of this network's subnets

ERROR: for 642f70c49dd4_peer0.practitioner1.example.com  Cannot start service peer0.practitioner1.example.com: Invalid address 172.18.0.80: It does not belong to any of this network's subnets

ERROR: for 03211a7c7dd0_orderer0.hospital1.example.com  Cannot start service orderer0.hospital1.example.com: Invalid address 172.18.0.100: It does not belong toRecreating c3c15520eb6d_peer1.pharmacy1.example.com        ... error

ERROR: for c3c15520eb6d_peer1.pharmacy1.example.com  Cannot start service peer1.pharmacy1.example.com: Invalid address 172.18.0.70: It does not belong to any of this network's subnets

ERROR: for peer1.practitioner1.example.com  Cannot start service peer1.practitioner1.example.com: Invalid address 172.21.0.90: It does not belong to any of this network's subnets

ERROR: for orderer0.pharmacy1.example.com  Cannot start service orderer0.pharmacy1.example.com: Invalid address 172.18.0.110: It does not belong to any of this network's subnets

ERROR: for peer0.hospital1.example.com  Cannot start service peer0.hospital1.example.com: Invalid address 172.18.0.40: It does not belong to any of this network's subnets

ERROR: for orderer0.practitioner1.example.com  Cannot start service orderer0.practitioner1.example.com: Invalid address 172.18.0.120: It does not belong to any of this network's subnets

ERROR: for peer1.hospital1.example.com  Cannot start service peer1.hospital1.example.com: Invalid address 172.18.0.50: It does not belong to any of this network's subnets

ERROR: for peer0.pharmacy1.example.com  Cannot start service peer0.pharmacy1.example.com: Invalid address 172.18.0.60: It does not belong to any of this network's subnets

ERROR: for peer0.practitioner1.example.com  Cannot start service peer0.practitioner1.example.com: Invalid address 172.18.0.80: It does not belong to any of this network's subnets

ERROR: for orderer0.hospital1.example.com  Cannot start service orderer0.hospital1.example.com: Invalid address 172.18.0.100: It does not belong to any of this network's subnets

ERROR: for peer1.pharmacy1.example.com  Cannot start service peer1.pharmacy1.example.com: Invalid address 172.18.0.70: It does not belong to any of this network's subnets
ERROR: Encountered errors while bringing up the project.

**Comment by kehm** [comment]
The issue is related to your local Docker configuration. See compose-with-raft.yaml and try to use a different Docker subnet (or remove static IPs completely) and the problem should be solved
