### ISSUE TITLE
Send create channel request:Start dosn't work

### ISSUE THREAD

**Issue by smartking260** [kehm/ehrblockchain#9]
hi.Send create channel request:Start  dosn't work in start.sh

root@ghasem-p:~/fabric-samples/ehrblockchain-master# ./generate.sh
Running Cryptogen:Start
hospital1.example.com
pharmacy1.example.com
practitioner1.example.com
Running Cryptogen:Done
Creating TrustStore:Start
root@ghasem-p:~/fabric-samples/ehrblockchain-master# ./start.sh
Recreating ca.hospital1.example.com         ... done
Recreating ca.hospital1.example.com ... 
Starting couchdb5                           ... done
Starting peer1.pharmacy1.example.com        ... 
Starting couchdb0                           ... done
Recreating ca.pharmacy1.example.com         ... done
Starting orderer0.pharmacy1.example.com     ... done
Starting orderer0.hospital1.example.com     ... done
Recreating ca.practitioner1.example.com     ... done
Starting orderer0.practitioner1.example.com ... done
Starting couchdb4                           ... done
Starting couchdb2                           ... done
Starting peer1.practitioner1.example.com    ... done
Starting peer1.pharmacy1.example.com        ... done
Starting peer1.hospital1.example.com        ... done
Starting peer0.pharmacy1.example.com        ... done
Starting peer0.practitioner1.example.com    ... done
Starting peer0.hospital1.example.com        ... done
Starting cli0                               ... done
Creating docker containers:Done
Waiting s for orderers to get ready
Send create channel request:Start

**Comment by kehm** [comment]
Hi,
start.sh takes the number of seconds to wait as an argument.
Try running e.g. "./start.sh 20"
